services:
  ## DATABASES ##
  # Main postgres database
  db:
    image: postgres:17
    container_name: eventapp-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./eventapp-db/postgres_data:/var/lib/postgresql/data
    networks:
      - eventapp-network

  # Bloc (s3) storage for images and files
  # Web GUI: http://localhost:9000
  blob:
    image: minio/minio
    container_name: eventapp-blob
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./eventapp-db/minio_data:/data
    networks:
      - eventapp-network
    command: server /data --console-address ":9001"
  
  ## DEVELOPMENT ##
  # Adminer for database management
  # Web GUI: http://localhost:8080 
  adminer:
    image: adminer
    container_name: eventapp-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_USERNAME=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - eventapp-network
    depends_on:
      - db

networks:
  eventapp-network:
    driver: bridge